server:
  port: 8731
spring:
  application:
    name: OrderService
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8711/eureka,http://localhost:8712/eureka