server:
  port: 8721
spring:
  application:
    name: ProductService
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8711/eureka,http://localhost:8712/eureka